### ISSUE TITLE
Migrate to Alpine Linux for smaller images

### ISSUE THREAD

**Issue by achimnol** [lablup/sorna-repl#41]
My initial tests show that it's viable to migrate to Alpine Linux for our kernel images.

 * sorna-jail works well if compiled inside Alpine Linux. (Binaries compiled in Ubuntu has glibc-specific symbol references: `__fprintf_chk`, `__vfprintf_chk`)
 * The image size of a Python 3.6 base kernel (without numpy/scipy stuffs but including jail support) is 112 MB only! (previously it was ~600 MB)

The core ideas to reduce image size are:
 * Alpine Linux tiself. The base image is less than 8 MB, just containing a busybox, the package manager `apk`, and a few utililties such as `scanelf`. libc is replaced with musl transparently.
 * Remove build-only depenencies at the end of a single RUN command so that each image layer has small footprints.
 * The package manager (`apk`) in Alpine Linux provides a concept of "virtual" package installation space, so we can easily purge a set of packages. Also, most Alpine Linux pacakges are made to be independent with minimal cross-dependencies.

Challenges remainig:
 * Migrate CUDA kernels to base our Alpine images. I think this is theorectically possible, but there may be unexpected glibc-specific dependency in CUDA binaries.

**Comment by achimnol** [comment]
Another requirement is to use multi-staged docker builds.
This is a perfect match for building jail binaries separately from the main kernel images.

**Comment by adrysn** [comment]
base, base-python2-minimal, base-python3-minimal, c, cpp, go, java, php7, python2, python3 images based on alpine 3.6 is pushed to docker hub.

**Comment by adrysn** [comment]
git, lua5 images based on alpine 3.6 is pushed to docker hub.

**Comment by achimnol** [comment]
For python2/python3 kernels, have you *squashed* the final images?
If not, please add `--squash` option when building the image.
I see too much size increase in some new images...

**Comment by adrysn** [comment]
Aha, there is an option for flattening intermediate layers. I'll re-create images with squash option.

**Comment by achimnol** [comment]
Closing: we now use Alpine Linux and Bitnami's minifieid Debian Linux as the base container images.
(minideb is larger than alpine by 20% to 50% on average, but not a few folds like before!)
